[package]
name = "overtls-gui"
version = "0.2.1"
edition = "2024"
authors = ["@ssrlive"]
description = "A GUI wrapper for overtls proxy suits powered by wxDragon"
license = "MIT"

[package.metadata.bundle]
# Install cargo-bundle: cargo install cargo-bundle
# macOS Usage: cargo bundle --package overtls-gui --format osx --target x86_64-apple-darwin
name = "overtls-gui"
identifier = "com.github.ssrlive.overtls-gui"
icon = ["assets/main.png"]
category = "Utility"
short_description = "A GUI wrapper for overtls proxy suits powered by wxDragon"
long_description = """
A GUI wrapper for overtls proxy suits powered by wxDragon. It provides a user-friendly interface
to manage and configure your overtls proxy settings, making it easier to use and customize your
proxy experience. With features like QR code generation, screen capture, and integration with
various libraries, overtls-gui aims to enhance your proxy management workflow.
"""

[dependencies]
bitflags = "2.13.0"
chrono = "0.4.45"
dirs = "6.0.0"
env_logger = "0.11.11"
image = { version = "=0.25.8", default-features = false, features = ["png"] }
log = "0.4.33"
overtls = { version = "0.3.12" }
qrcode = "0.14.1"
run-as = { version = "1.2.5", default-features = false }
rxing = "0.9.1"
screen-shot = { version = "0.0.8" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
strum = { version = "0.28.0", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
tun2proxy = { version = "0.8.2", default-features = false }
uuid = { version = "1.23.5", features = ["v4"] }
wxdragon = { version = "0.9.17", default-features = false, git = "https://github.com/AllenDang/wxDragon.git", rev = "8f64163" }

[build-dependencies]
embed-manifest = "1.5.0"
embed-resource = "3.0.11"
